apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  namespace: openshift-lightspeed
spec:
  displayName: OpenShift Lightspeed
  image: 'quay.io/openshift-lightspeed/lightspeed-catalog:latest'
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
