apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-lightspeed-operator
  namespace: openshift-operators
spec:
  sourceNamespace: openshift-marketplace
  source: redhat-operators
  channel: stable
  installPlanApproval: Automatic
  name: lightspeed-operator
