FROM curlimages/curl AS oc_client
ENV OPENSHIFT_VERSION=4.19.9
ENV OPENSHIFT_BINARIES_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}"
RUN \
  url="${OPENSHIFT_BINARIES_URL}/openshift-client-linux"; \
  uname -m | grep -Eq 'arm|aarch' && url="${url}-arm64"; \
  curl -o /tmp/file.tar.gz "${url}.tar.gz"
RUN tar -xvzf /tmp/file.tar.gz -C /tmp

FROM curlimages/curl AS rosa_client
ENV ROSA_VERSION=1.2.60
ENV ROSA_URL="https://github.com/openshift/rosa/releases/download/v${ROSA_VERSION}/rosa_Linux_x86_64.tar.gz"
RUN \
  url="$ROSA_URL"; \
  uname -m | grep -Eq 'arm|aarch' && url="$(echo "$ROSA_URL" | sed 's/x86_64/arm64/')"; \
  curl -Lo /tmp/file.tar.gz "$url";
RUN tar -xvzf /tmp/file.tar.gz -C /tmp
RUN chmod +x /tmp/rosa

FROM curlimages/curl AS ocm_client
ENV OCM_VERSION=1.0.17
ENV OCM_URL="https://github.com/openshift-online/ocm-cli/releases/download/v${OCM_VERSION}/ocm-linux-amd64"
RUN \
  url="$OCM_URL"; \
  uname -m | grep -Eq 'arm|aarch' && url="$(echo "$OCM_URL" | sed 's/amd64/arm64/')"; \
  curl -vLo /tmp/ocm "$url";
RUN chmod +x /tmp/ocm

FROM fedora:41 AS final
RUN dnf -y update
RUN dnf -y install yq jq awscli openssh ssh-agent
COPY --from=rosa_client /tmp/rosa /usr/bin/rosa
COPY --from=ocm_client /tmp/ocm /usr/bin/ocm
COPY --from=oc_client /tmp/oc /usr/bin/oc
