#@ load("@ytt:data", "data")
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: #@ data.values.app_name
  namespace: openshift-gitops
spec:
  project: default
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  source:
    repoURL: #@ data.values.repo_url
    targetRevision: #@ data.values.repo_branch
    path: #@ "./environments/{}/{}".format(data.values.environment_name, data.values.gitops_dir)
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
      - SkipDryRunOnMissingResources=true

