FROM curlimages/curl AS ocp_installer
ENV OPENSHIFT_VERSION=4.19.9
ENV OPENSHIFT_BINARIES_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}"
RUN \
  url="${OPENSHIFT_BINARIES_URL}/openshift-install-linux"; \
  uname -m | grep -Eq 'arm|aarch' && url="${url}-arm64"; \
  curl -o /tmp/file.tar.gz "${url}.tar.gz"
RUN tar -xvzf /tmp/file.tar.gz -C /tmp

FROM curlimages/curl AS oc_client
ENV OPENSHIFT_VERSION=4.19.9
ENV OPENSHIFT_BINARIES_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}"
RUN \
  url="${OPENSHIFT_BINARIES_URL}/openshift-client-linux"; \
  uname -m | grep -Eq 'arm|aarch' && url="${url}-arm64"; \
  curl -o /tmp/file.tar.gz "${url}.tar.gz"
RUN tar -xvzf /tmp/file.tar.gz -C /tmp

FROM fedora:41 AS final
COPY --from=ocp_installer /tmp/openshift-install /usr/bin/openshift-install
COPY --from=oc_client /tmp/oc /usr/bin/oc
RUN dnf -y update
RUN dnf -y install yq jq awscli openssh ssh-agent
RUN arch=amd64; uname -m | grep -Eiq 'arm|aarch' && arch=arm64; \
    curl -Lo /usr/bin/ytt "https://github.com/carvel-dev/ytt/releases/download/v0.52.0/ytt-linux-$arch"
RUN chmod +x /usr/bin/ytt
RUN ytt --version
