apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: openshift-opentelemetry-operator
spec:
  serviceAccount: otel-k8s
  mode: daemonset
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      k8sobjects:
        auth_type: serviceAccount
        objects:
          - name: pods
            mode: pull
            interval: 30s
          - name: events
            mode: watch
      kubeletstats:
        collection_interval: 20s
        auth_type: serviceAccount
        endpoint: "https://${env.K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
    exporters:
      debug: {}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter,batch]
          exporters: [debug]
        logs:
          receivers: [otlp]
          exporters: [debug]
        metrics:
          receivers: [otlp, kubeletstats, k8sobjects]
          processors: [batch]
          exporters: [debug]
