environments:
    example:
        version: 20260124
        # alias_of: Alias of an existing environment. Keys defined here will be
        # merged with that of the aliased environment.
        alias_of: ""
        # depends_on: Deploys (and destroys) any environments in this list, in order.
        depends_on: []
        common_options:
            # common_options.ignore_installconfig_check: Ignores checking for an installconfig in this
            # environment.
            ignore_installconfig_check: false
        deploy:
            # environment_vars: Set within the container that provisions/destroys the environment.
            environment_vars:
                - SOME_KEY=some value
                - ANOTHER_KEY=another value
        # these secrets will get mounted into a folder called /secrets within the
        # container that builds your cluster.
        secrets:
            secret_name:
                # name: the name of the file that will contain this secret.
                name: example
                # mode: the file mode to apply onto the secret (MUST be a string)
                mode: "0600"
                # encrypted
                #ENC[AES256_GCM,data:Xt1ZYFjzKLaxjYHfiaHRBbR4ALqDdq4IOBRWWGWNIzKgL6X/fW6zFnR0JK3zrZ4W+8fY0y4QFQcEulo4gkUfcHR4w9CEwpk4dOV5/mxclZaHmi0+ntAEKsVNFhWZffm4Zw==,iv:ag2f2hiaab//bSz18kfkp8/PuNX3/hCepmFSr6u5FJQ=,tag:wNjb3Zp/KtN5gI0UUDJIJw==,type:comment]
                data: ENC[AES256_GCM,data:cOAidsZYdutElgs=,iv:afe3K1W+hMEx72ozBSPD+7UQeUyW9xNT7O1kE8p+moU=,tag:qbMQrZBPup3SKP11XXJ3pw==,type:str]
    osv-disconnected-vma:
        version: 20260124
        alias_of: ""
        depends_on: []
        common_options:
            ignore_installconfig_check: false
        deploy:
            environment_vars:
                # encrypted
                - ENC[AES256_GCM,data:kSHOb8EXglo13u5MjqhSZsFWu4K89EShSWCNOEBNGUFyi5pzTQk=,iv:6VTONzadkk8hK4Fok39NMOL+J/0jL9sSWncQ/RUd3oM=,tag:0LA1sK88rKYtjOsWehHIGg==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:a2m2mT9pJ80P7QjijQ1TVHFJrNxcCNeJ1vdd1hcl0SJwNkLEtn40CayBvfMzNyctV2uAK6FuF0wLw7NmJ6k=,iv:XDwgXzdzF0LaMCYCk34WQSZV+m8FouAuZX3a1sW7H4U=,tag:VC1J5N6PmZCpAF/7xL78sA==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::130164124975:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:XD+XKnpzZtkY87rFO8ePvDJOf18acvCTBTs7+l0zkr3D7xxD7iSqYEINDtDHaTy9s/Rd,iv:A5CAACpt9wlcxMCrtJY1elaOuG6kx/XH7Q4kIW4RB9g=,tag:mlk5IlvuB4LXRSkzfmM9Yg==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:U/eSzTB/Qy+H6OM/aAoTasAE3mXqhETiwT5Shp983vWdWowDOBhgDOAidA3+BgTBz9UDe6kceKuSLA==,iv:hp/LbndfsKOkmQvyz1mCremVKAvS2mkU6pEQoblPyoI=,tag:30C0oQpJAoRfSKG1pXse2A==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:SljBndr6TwMPfInKgr+4yiptPNY=,iv:p4ppB/QbEL7PKRUl/+OJpzhjitLO9EOGrxFy6WxcRss=,tag:7Mf1J3M93slOIAi/lE7XwA==,type:str]
                - AWS_PAGER=""
                - TOFU_REINIT
                - TOFU_DISABLE_REFRESH=1
            cluster_config:
                cluster_name: osv-example
            cloud_config:
                aws:
                    compute:
                        instance_sizes:
                            vm: m8a.large
                            bare_metal: c5.metal
                    networking:
                        common:
                            availability_zones:
                                - us-east-2a
                                - us-east-2b
                                - us-east-2c
                        connected:
                            dns:
                                domain_name: sandbox3253.opentlc.com
                            cidr: 10.0.0.0/16
                            subnets:
                                public:
                                    - 10.0.1.0/24
                                    - 10.0.2.0/24
                                    - 10.0.3.0/24
                                private:
                                    - 10.0.251.0/24
                                    - 10.0.252.0/24
                                    - 10.0.253.0/24
                        disconnected:
                            dns:
                                domain_name: private.network
                            cidr: 172.17.0.0/16
                            subnets:
                                public:
                                    - 172.17.1.0/24
                                    - 172.17.2.0/24
                                    - 172.17.3.0/24
                                private:
                                    - 172.17.251.0/24
                                    - 172.17.252.0/24
                                    - 172.17.253.0/24
        secrets:
            ssh_user:
                name: ssh-user-bastion
                mode: "0600"
                # encrypted
                data: ENC[AES256_GCM,data:iupgHSVM,iv:8HQX22P7WxIM7Qe59YyiEsi7Xu0FCGgCHKQrCixFcsk=,tag:GxJ2mK+3cS/AWaqvmy+m6A==,type:str]
            ssh_key:
                name: ssh-key
                mode: "0600"
                # encrypted
                data: ENC[AES256_GCM,data:lxYb9KtzzB/79Cu/pNxAmrIFkMdSgVHTbkVVZQFnZL9GkM8z8IQOOb/mDPScNQr19cu3Z+NZ3mD26gq1ZCMZU1A49YC42GDGu4dxzM/SoEIcjNj/nKS/kkmaoItMoXNO2C54Bfef7wEmvnFhWbyZQAiFRj49BUFLmRs6oN607yXepfnvNHRGybdJ/vUAgts4tBd9RJQY5vwsGkb4UdAbeTUYK2pCEGEdxiCd8YB3t6ZUwgSpmwTzLGZ/1pBXuRjY95KGlNaGr2MXYn7cqY5vudNZczyaACBwxxFuDXgOAetCT3RurpbYgU91aglYZO3zNuTfBwpXo90kBoJSAVCU8bvlV8w4Mn6hXpXwLUvWHNW7cQH2ih2+1H2CKeDaQalPD4SqYL5UYEYbzh+GXlqag7m6jkE74Fuk8WFJpMw3XeBycnwogdiNA5t9RMKbc6/ISPTWeI6C8ycYuT5z8u/VeD5B/4ZiokTBtUcS4Z+XYDPSizeKLw+3oeR0a0/mo3KVtKbYGkcaDf/y5B62WuwB103xIxjabNSauvysVLLp9RcwS5qohXd/Vw0vBZ4XlIJnAE4OmTrTqupXFQK7Dm9Vdf3cDl6ZCvKJPy81ltWp3jKHdVVTKcs5rZZFH/4FqVOeFWThMjaMj41cBnJnUtqwxRBGzLtWRZO+/wE+aJv55+QBqneQa+IkROXb6Nu3Bo6Em08mqR4nDOR2dWkU9pe1C5r5CM1Go5NjSUMpAmWSuRANd+ToJ7HW11ztygtAOfjmpCsvDg5Bn/uJf+iLZOmxLGc1Ve/NzQ+sU46iBGlwahx4TCbuoJHYJTkKWvPltDmNCnsdR0rGw5iXkHw7Ny+c5qxmjSfNftn7JGIqjPN5EftXMfUz62A6w9iNj3BtNxFNOuv/41QhRZAf1Oi1yV5+/235MKgO+ow0rIXx4bQeMJ+Dc39TTmQQpF4PRWnmVuctVbTD4iZizDnOZiOb3Izolka5dsROKCyrwan8NSgjp+qwieGSgTWFSBq5dQDP7KVHeRg/8yrFpRV396t0GxdZhhPgcVeK9XW5pNOkcsYXCt8GaXFIt5+MvVQcPKk0qi7DG88hhFtkqmhVGFf76qTlwQBaVyvVYi0Pw+z/EbNIKm8P1dmUCQFaNNGJkWl6a/F1ieqF0wm6IKgbdYbRySTGU3KIsJa1xakObTzXPvFSQVeGyQOt9WJ00OMe+cXwyNFizBMSUyMcKzpOiV4nnu0NqXBaA8Eey28Kr35kgkuhRcgbZy8IFVeGlgkjwLcacb1x1ijzvy7htInLXU69r3w3/pTNSmzfi83w/WOguh3BjxG/AqtvbCrVGL4/ewkfOMoBmaWGKtDx7oozin3RFsZYKUFscCvhjiG+yWvoRQVKHju2HtItYS/NNG6jHrpAfd/L5itbrROZ0if/tyhTmL/g4Jldd7eo1GnqZUsadPV1qZSs4Ltt7A5gSam/7+5VeWQLEZS6KKXA7T5uEjH03q8qnfmjDRah0VdKV57IseSYr4bH//8iq9pnAPBNNVnu7ozijQL0ijZmD49CR3Xd8HDn6DIo4fSKqmeOUu0uCH0QVbkP9u9gBXfKStOe6bumy32uh1wE9PEJjh6SiDrBVu1wjGkrjL3nO4xTzw6eORtkqRBRlQNk5i7DMsyWMU2HrIB7wCTJhe/FT8fgIVoD85GgUqA9HDxepS4/p8NL7Y/DZ5s/Te+WXspOROcSM+g43REODLQKWWzVXmO/C+QoOKolb5qy5ufL9fonScs46bFBi0m9aRqkniM/js4iMo8g1BHwHX0isiXu/R1rBPmCpozVBQtYKWZCYWOz6klZpjeTE2ccz6NjWETwFAibdc7JR/ZnX+ltDTmFp45lghmSE21Wf/FoX6opZwuZHa4+0CVvGcH4/Z0vaX30lqb7BZl6OonWsQDmYAY8x7vt+j2IYs8usbNX2voXPQ9Zb7C0TyPYgqv3nrud7g6YZokFN9rSUNwjR7c9p4VknhaJLvfadFjxumDovXBpFjPM3i5WfEfxZkeTKx3GI/wX8/tVQG7XyiErCEyk2tLjGltYUfeU4+D8JYouuEW01CZKdrTUINmbxrBNixqmFQ0S2ZgSiiYa4sz+/wwBBIE1G2wnZD/Pxt6OSh/MJG1XaTLZAFyoqDU5sF7/bUAjqL1ThmV1fErkI83VJ2qbmkW6qOinJhreKEn7haErAzFT+WLqRsStVKj+UGJYo7SvSaDL9Dg2rwy7fToKIrmasw9x+8nHUYdRQjMdfuIy3YFhoqxcdKd9COg1FmVPqOnkV0TXh+EWV7ab182YPVNoIR5sPg6YhgD4uhZg65c9FuGoeMCxlpIxtCOURBKBq+sbgtpAV7RMAmj7QZZfwr6s678rCZmnUtdxFXCIY3pzC6vFyNgRB3giUn9JuQ3Z52IBFVZguFB/sLkknfk9mPUUpCjgtetj7ZtXcA9tY0m5WSPLbfsm8/iwPAlsGUl18a9VZKX8yRPs27Au8DZCHnuwXrz6D3ZCyYK0Rxj8qEW4V2kmCgaSDKBBUHIdeAkVMmxlaZXQy3Yv5VDVdSrs9Zg/NdrDR1vptLrwXF/LfLTL0/mMk75GU9HP1kKg0KLQK6b0A9Q9VjzNrXiq9H7KlPF4GzF8IANDFdEiyPZkAXRf3Jbzkxoy7jiu2LH+2SEA6WAggfbxwERITep7mxOGt5J6o+gsyZYomz2UNMBvLs9mmjkFA/E1xB9QwJa1Vr3JjraDVv42unEyeJjNHunCtpb8GpDP68txJG88GwItQ6D3LRKIy3fEvOdR7c8U0bKeRTPA8WXtu9NT2Bny9WuKz088t3H/KH4ZIeQl7CStS/hvA4Ronv2Xvd3DjhqcZScobAmbZpYobABhQTSxjIabRQQ2LJf1ODDs5ZijH2yOUiBIwuP2qqPvPHpP/5Ac/+lWA3cEgpw2UrdfH/Qqz0ekpWkQ0pw/5yZlncc3ZXHp8hlV4M9lU4YsFUKkXXuXrvNyw5csQ8Y2HcsOB8Q8WWvLnk0ggGHr1CI+lnJVUGrMc++2V4PF5R5BUbeiHblmuYEOMZcao3Zkum+m45RCuwLiu2RzVYg/GcyVxiChe4j7wSwa2NQ5iDm32AQziCnXE2FjdxzSJAndvSSOwNh6Fc8iYP+WraOQkWVWT20+NMKEVnlDeFe9nzPh+P6UEAJB/WPgtUW3agaWt4B29mnac7KdW3edbuTt9QQKnF4hjpFS+ATGCkT1u/16gawxk5FNUcmWEFGb4lOGYEiwvUUB3hSqrUnwfcLCE3gmfdM5PlT6EtivVjwvPDGx2LldP2WvJiH5UpPugCFBjkvVdwofazh0lfb7FvOjHM+YyRkbE+q/i/xzaL3Z5wZTidkiuLo16O6fi1BBcGrwYKoJBUo6Vs5NIWfu/DRICHQ2IKUZXuqMGpn8VJQVRBeSWINIQJTbrAqom9L+bp9KL2ss61A/BUWVxVTHOJVmfcdQjQ==,iv:S/E4mPDwfMA1vJGKyZw1PifypSaYMZ22jqKR3NHYemI=,tag:JuccUZDc1vZ5Zq681zdptw==,type:str]
    rosa:
        version: 20260124
        depends_on:
            - ocp-rosa
        alias_of: null
        common_options:
            # common_options.ignore_installconfig_check: Ignores checking for an installconfig in this
            # environment.
            ignore_installconfig_check: true
        deploy:
            environment_vars:
                # encrypted
                - ENC[AES256_GCM,data:S0U9VvYuFTJ4xFX+gJ7xSIr+5N0N+do7XOoof9rKZ4gOm7skRVE=,iv:tXOjs6tQRypZwU+eMhFIk3EbqxfLXO/VFXbCsNd95XY=,tag:7osC5TqRRme0m8Po4mr08w==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:O09DmB3DvOKWOrANVOL+gVi0N3fuuh+jaB1kSI2lNbBzX7q4121lPjMO8XW72GORTkwwGw8e193xg3J8Ujs=,iv:33luVHwj0HgSAVoTGA7eN/3uh7ZQ8mZdEXwg3VYbZFE=,tag:/uGoak5Vkcyeu/ObMIsqXQ==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::829168431290:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:0zy3L3sVDtrqKEy0rWRQ4ALtiaX+Ec5flkhTcB9gTXOseRUWCjZBKbn1yerNKSoOcyA/bQs=,iv:JkiHxfBBlkm7lsAZkfqieXTrTIYrC8lfaQRh4Tos/H8=,tag:wcmwbPCEcBpMAmqGymJAbg==,type:str]
                - AWS_PAGER=""
                # encrypted
                - ENC[AES256_GCM,data:NaWQ9lNWGii9gRsM8ZD6eH4lH87RYhv9+eAjiEjr12Jfo78A/2iBPNF1V9s9Tbu4cu3k,iv:3YY5/q318zgBNcGvH8thQxTRgJ8lnVfLFk5KlEEair0=,tag:RtCkrrnghl291NuVmkEfcA==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:uFVnQVD02n6Oqtc66iWJv9DLL7SmB5tIpHT+cStD6woI7b2gB/xZ+r1NDgnLi7tmhzln,iv:oI3OhoX6TN0uimRabih++nPUDrhtpNNyO1iIlcyzAIk=,tag:Yphaxv1NARnHY/UXW5/GYg==,type:str]
            cluster_config:
                name: rosa-demoland
            cloud_config:
                aws:
                    networking:
                        availability_zones: 3
                        cidr_block: 172.0.0.0/16
    ocp-rosa:
        alias_of: ocp
        deploy:
            node_config:
                bootstrap:
                    ignition_file_s3_key: bootstrap.ign
                    instance_type: m5.xlarge
                    spot: false
                    quantity_per_zone: 1
                control_plane:
                    quantity_per_zone: 1
                    instance_type: m5.xlarge
                    spot: false
                workers:
                    quantity_per_zone: 1
                    instance_type: m5.xlarge
                    spot: false
    ocp:
        version: 20250827
        deploy:
            environment_vars:
                # encrypted
                - ENC[AES256_GCM,data:iRENeAfN/wKgZBU4cFKa57nniYhlq7kqMbMNtCWO35lY61q/l7s=,iv:CXttwpqzhH5FFri63FacD09/H1IYRDpVlQtAwpFb9qA=,tag:FtG4vVLefxl1N6Vj3OV04A==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:NqfGU5saiYTHORBN88Mb85CyKIwHxsgkFtZqF4ak90Z2o3gXERD8fQjnUDGTZD7YeFfH1FTCZ+4byfbe16U=,iv:XHzPBr+M30y10eh6KIscKWRbuRgYfqrvZqNuaH1PdE0=,tag:0DwIMw10VqPCX6jqkpS9Jg==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::829168431290:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:UvIKwAXZ8YeatpIm1yCEOksEMK/kuk0oJo+cNQ7TI/vmcnpY6JC22Dm6UJCC/D3ZeJ7Ft8U=,iv:ye1xbwLiAmhOjI8db+971grozYU8JTXN5dR9n+Cc5fw=,tag:IzdRi9HYk6nMWBTbv4C4hw==,type:str]
                - AWS_PAGER=""
            cloud_config:
                aws:
                    cloudformation:
                        stack_name: demoland-ocp-aws-cfn
                    networking:
                        dns:
                            domain_name: sandbox1365.opentlc.com
                        cidr_block: 10.0.0.0/16
                        region: us-east-2
                        availability_zones:
                            bootstrap:
                                - us-east-2a
                            control_plane:
                                - us-east-2a
                                - us-east-2b
                                - us-east-2c
                            workers:
                                - us-east-2a
                                - us-east-2b
            cluster_config:
                names:
                    cluster: demoland-ocp-aws
                    infrastructure: demoland-ocp-aws-infra
            node_config:
                common:
                    ignition_file_s3_bucket: s1gdf449ohge-demoland-ocp-ignition-files
                    # encrypted
                    pull_secret: ENC[AES256_GCM,data:Q1svEp/2mSIJgaWVcuwRUXKYZl2Fv5r7pfVapkCpTmHIo6bT1ADKIm9O31aR7wvgHBEYq+VDLpitXpctEAoxGuLMeyg1oCJxPixQA/eB/mf/pKmqFPiZj2TJgVrro0oV88AsvvLzpNFwoyTgaJks8NIy+tyz4i9k19kbZ6FT5VCG8NkKtRdv+SWeKffTUaDjhXbsBEjpE/aBsZal8pMXNSqNnQmsTLdYtDwfUZnI7jYz8con2L0BqsHWRZXEA9UEEeP872F5WzOpAun0viYGcVCqKJYugSvwS6CnvQdyrhRebzaKUF9ltPCTLsrhJGJWbUirJ63maShtO9C2y6J81rPStgmnsojsmHWj7u8Tu9nF/lRoG8+Tc7akivlkS22hPI80X2ecMoMY7kdbIPK/M5tGDNOnxdz/Xlrk9CtTOSkjOC9NhJUGBJCDuua6HoKW5oixj9eWI0jXLw4doTVH9OscE6hwZw1qWqLnCTv8lRIQeA+fEpzqR6TYwHAdNLudyQqfB5BCELN0baZaPtUAie3jYnTPGBcQ6BkMkhPkcnnx1uwWjl/z4reWaELshezm/h5GmFbV3tGFruKvzSA3S3Xzb/JLnuuqlJbH7fBLB/+DRo/dV2jRMdThBAYsjrx9hZfOv9SwQB9SiWxikFut4Gk83kWLBQJ5NuKgvRHYygCqov8ZqQT/S6wX1/+5bhjSe2x41r2irbLYRc4LeqwyQWbpCjyXsg7hYYnH1qOSjocoLOp1i4R3CXx0M3N6re8OdxKYQ8s4MNuXh//uEF/To/NVk4VIKBdIq84Eo3J7EDGDs20GMHXq/K8VRZVt3NXlNGc+j08PdoXO2FAVo8fGtIjANdFt8nnWpcPLPBwCFrUpv8jeBKPEMXT/YwOVIS9JMTwr9dz2cCwln6TXWv1LBMKhk3ZNBMHQm9aSZb3oA0LBRInA2A8tUtQWdkddAEck3Q4Kcfn7qr4NDqJ1XHuum4nTWkEhbZcsWhyLs2FZP8kUD/bt8+qN04dC/OsvhNMs83SbGCNG9iX5DqDvZ3LKof/sKgawJlwowMt/YIXRflWJKcucXx77PueCNDY8ICR9Uwsg+Dn+Cv9e9BceYB3+ng6pLfI7uT6v+3SOfsuaRy8/z3PiNgZT31ZQFPKB6zftvXxqDfJwb841/U+nbsD6ulj6kP2oXr8KBvg31nsBCWyJLcsR1L5JjRRdV0NLgi9cNjsUn4wuB4uz9x7wopMrexs2TLpFxGnMx5yL5svg0/2jkzeg9j3ESGfOLLJvIAUtHHeyOPiCobfMM/m/JYTikUBitSOQQSx8BRMkpv7hEzc+xQGRI0/3QMf8NSD+JnI5VCFwimp2ihJFyjEuUpxpJl86iCRT91DEWjkAuhGthDx1g28nm3+gVbW5MCwElBGxarABZDJ4bfC61ETJv53gqQt2pPAuGGsNJdA1ligWLTkeXC/rTcyg0nWuZwXm5DWowifybOSAQ29jsxUMd2jtQd6jmKUgKAOsvOGvTyRn1qdJhbrr7nePPfDjZ8loRKAAA052bJbcJ3h2t/1yJSDRLPO6RcEnvofUAON+TFkc8WMRJ8qQVowi+iUXRs2U4M6pgVd8d9fmLEydpo2iBRsyjf3Vr0oJVh5LizsUKuhlwKYog6atBfdT5jA5DqUETBy5cAR8q3bcLPImaPFUt0KDbnTtuX7Jx5hDjal4QMWzogFPxDStFgL/FLH5vb9n8xIxQ1dbEuFm1RwJ91+pQUokfibL9+j3HTautTtrAbzB5dEnbvmuEZ/zJJCNXx5YqBoTmLywKy4dJ72Juul+8Q/WxOoQ1K7qbDaDtDjur5OWJ7D1AxnN5NgKMcyjVU7IaaCtfLw2J+Jt7mMSXgrW9nDg8+HKbxPJdmgnqt4MmKsmEXYL7WxNgp9slOz91ri7wH9f8UP37bND9UvN8VGmj4pB4X67SVl0xs6Jj7V3+MMyDdIxLnaGxXA9oTUV8uRJZ5wOCOsaNQe2FZBqn+qdilGiIwqcIYznDxPjGT6FcgO88plTsAK40LoDlO3ZyG1N4YQ1ajjIj+NCE328KjDnWrh3h8QZPbGQQ60n4sV6s6NH+FEFU0uhfwCDO9gsiUHZLU0P++4lajUcW10BPAEFjzgxAfTwrqCAbyidceUAPiQzAuY8atGiaH0Z+e7e1T0Httz45oVufzbJ6Xb32iMARvn1WD0ZmjJ7nRopZnnyj6C69SqbYboHJxU4T1J0r71A3h1j8HGDzKvW4vGVzy23cj9mZTOKs1KjSnWcGsbNxwcS3WeC2SlMUxPvnVN51lF+AOwFxgaF29RqdLr4pS4KjLpqNMrOeBDIlW98maVQftxTjT2RyK/G295Usj+aW/4B/1hShSzobnhP2n1NrbGkOUT4Sn8KYZheIJg5ZRoYvfOj1d6R78+gijOU3XUcZ+4EsGwvOs3ZWVCtm67U+csIF/H7P9w5jvgRcItYzJOyb/GBRnAq0ZqN/vz6r24ep7lSifcm93nfQb11b8d30gLkMMNK2NE77dVlL9nDNpC3+O1FbIArPHJ8nufxkqzqDnjsY6BLZllN7UAlvXhs1h34cPA+hA2L4Te2JPdwsjKiicDeikmXIWcrSfjQI8/cnGRGg8Y2zZ52es+z9NzAZHZwkjgFw6/Q5CSyKPEMM5EG0Z7d5wwPvqJ7fBEiPCzW9YHNpOJqxQNk8El4OKdHwGBsC12uNfiRYxKLDAdV/X6L0+QTsZSF5cBh21NVvoBFONPGoyXm1eEvDpwAK9THpQSgngGjAUc8OzxABK2YAcHN6XMcY+L5fSAMUvwRf170oi3Xxqz+CXS06woKybTyeBidwDb6xdkluWPifUjeXVgb3cOjk0QXOopbgMCDHvkexF5fUJEG7GiUFdiDcXlaCMkVwWNruxdktIn/TKRu3OV9aWT9LNa2xH37Fe2Pcp6gOoMIfld2NicmBv3cIt94hcctoVW+89s67JeqDkdfO1l3AnQSauujuBpbttiUR1v5mFfAciDfTWH8kuefm1FsGjW5V2YBS3Iv7wIIVGL7EerD5XPAGpU+t8NpAI7HZO48y2Q6ciBpoatub+kO4BIJP80/QKUJ5M2OY4pOFJCCPvRblAIbbOZXELegCqSzCX6SO9UcYWxakN1tCEKzDcmMXfZTUL/i2kAy8aSo6WdpVBIXc5xYEj+kB1TKix6hfrSmmatCJWvH7en5ILXxmSdcTg5s58VsEb68H+eoTmB2riVOzK+Ei1iKHQwpDBjWfCE2s7/Aj4oVblC4vxwi1twHYnO2UCeWtKnzIlhv2idYqHZh4vxV9gxGkZ3P1kb76gHESn28w21v1Sb9yBaKbqyB6Uopvuii9Qs4f8uDmsPTVwmJXuXQbmUt3DEZWaLnE3gH+LuVigIXhTczRC4zHh2S8TMdnw79vz9ZJT9LqG+z7sRmnlCUCFSN2Ra+aUH5kr/1vJlce5jAfPA/hsE2kSUsOGffqMauB1novNsj+6Liw9FyXTuz1WPs2mlocCJl1sMrC/Lcr2mHhFPV+H1uzgOML1FGe0DuHA1yJm9VjX+4WSICXbjcS/xpYl4JYjVYDESna3aZNHd/qVtoVoRXUdxroAN0bExpL3sOrelhd176T64V7NHYqo3o6XiuOFv+lAk6ovogDAdDdRswMvo2zFxsXdjttKt+G4/z7JkG3boFbdXpdJay,iv:eQ/2mP9+lNSOgXHhY6v+dkgAhxpH1IL++YGPOgguMdQ=,tag:j4h7/zKX4jLq20SRq0pE3A==,type:str]
                bootstrap:
                    ignition_file_s3_key: bootstrap.ign
                    instance_type: t3.xlarge
                    spot: false
                    quantity_per_zone: 1
                control_plane:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
                workers:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
            secrets:
                ssh_key:
                    name: ocp-aws-ssh-key
                    # encrypted
                    data: ENC[AES256_GCM,data:U2eobbE6upIEWrxHBbiL1zSEMdXQBDwRWpiZyGog9UJMPT/JwpXKdy5pD0wR2O3Gg/QVR2lJH4pZGJum/Xeuccm6/rFfxLP913xX76Ps+W6AP10YowpbOAjcX/bubm+FA5WZnIs0CFr8LUSzmKzrKxv1ITL5vxECbXOseszrMvBnDUoduAj5b8X31/FmPzPJQ1hBIQm66Ko9qB5yY09MpxeWmWOB4ZjR6n2tbsRve886UEq922SdhaldEozb2zq+OC4U1eKBOc4Rq0JoWCam2NnM/Y8vCrgOd9wo5taB+RAR4v+0WqRZlZtFoRxv8L2BAZkuZ3mObqbb5PcH/a/w5HzJ/V82mm5UN3Ie6rBLR1W2SsdWh4ZHE2qhYMpgU/XreRTGwG+/b3hU/z2ik7wgVo7MIXTvDpGqN8tf70IzmMXX2EpHWQMAO4Re+UB8b7GP7xFREbCjC7hnFQoel3AJNUPVdFFsGFdgDHyRa09BamVfnlhWtVfChrY2xl1X5NroZZT7Qn9uOvw6gj7mJhrmbq0JfCaetecTwqY=,iv:/j7qGCxTK0lBUSONjta9cn2A3X4idjk3zamBgFkFLbc=,tag:IR2K25bjQdDe7+KU/OyyCg==,type:str]
sops:
    lastmodified: "2026-02-20T18:15:03Z"
    mac: ENC[AES256_GCM,data:CGP/mQzIv9p0F2v3zZQ70kCCKDZG7zHWvylH8mP7Ff+SxFZK5zj2j6sMdJX6NMmmtyMkLvA97IcJUrrYxAS4jFbG/7BeAbyu9Xu42UvYMUsjo6IhWwP3MyQ1cB+SOVyocsZ7YYzRSqCMnBtbydHbVupHEiBOeuoNHAVGdT5ZjME=,iv:OPUDDbDoeM51QQK/DuLT93yX6sLrrA4sC8WTuYl/xvw=,tag:ahHEGvaesRWuq53iGlDW6A==,type:str]
    pgp:
        - created_at: "2025-08-21T19:30:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYyNh9fWacSISAQdAh1/D/6CIXWPHdZTNp0ZI2lXpcWcYvSQCewb9uwaDJnQw
            ipjRcoFwW+yp4GHfMJcW0j0HE9AMaA2I9rMO0I8uq49axieaTe3ILpfpFrV4ThP7
            1GYBCQIQrc+2di+Am+TGhRxvmQfECHp7X7+ZUwk/TSjKRU8UOdXICAOkhiVVfJuW
            jafsv5O9xj4G1pGPkljda5ej3Ny7Gn25b8WuazE7IMDq7K9u/cheoCWDf9Wln7J7
            QIRW4e2GQ+w=
            =Jv7T
            -----END PGP MESSAGE-----
          fp: E7645036F453F0DA44BED49F49949A5572BF2AE4
    encrypted_comment_regex: ^[ ]{0,}encrypted$
    version: 3.11.0
