environments:
    example:
        version: 20260124
        # alias_of: Alias of an existing environment. Keys defined here will be
        # merged with that of the aliased environment.
        alias_of: ""
        # depends_on: Deploys (and destroys) any environments in this list, in order.
        depends_on: []
        common_options:
            # common_options.ignore_installconfig_check: Ignores checking for an installconfig in this
            # environment.
            ignore_installconfig_check: false
        deploy:
            # environment_vars: Set within the container that provisions/destroys the environment.
            environment_vars:
                - SOME_KEY=some value
                - ANOTHER_KEY=another value
        # these secrets will get mounted into a folder called /secrets within the
        # container that builds your cluster.
        secrets: {}
    osv-disconnected-vma:
        version: 20260124
        alias_of: ""
        depends_on: []
        common_options:
            ignore_installconfig_check: false
        deploy:
            environment_vars:
                # encrypted
                - ENC[AES256_GCM,data:TdnLS77re/pHyvYRbOkEkhBd/1xDtfGlG7zLxVnFZ9wYzsSgWgw=,iv:+dG/3obku0W41mA6NeeOFFH3h80K32tQ8rzurKU4Ecw=,tag:oLP6dq/kAA17sry6Sbx/JA==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:vYwADjXqxvqWyeqjsmHIF3/ae7/uucEoFcjLfthbXlf3udiT4GCaj+mqz9WDBqzZhgaE1WhfkYlwxKxueg0=,iv:wSnWl8YTKBWN15pkoTipbZiL8CXrd6xmdl7g+5MDsDE=,tag:mQbSC+XFlPYKnMuCU/bbbw==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::130164124975:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:XD+XKnpzZtkY87rFO8ePvDJOf18acvCTBTs7+l0zkr3D7xxD7iSqYEINDtDHaTy9s/Rd,iv:A5CAACpt9wlcxMCrtJY1elaOuG6kx/XH7Q4kIW4RB9g=,tag:mlk5IlvuB4LXRSkzfmM9Yg==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:U/eSzTB/Qy+H6OM/aAoTasAE3mXqhETiwT5Shp983vWdWowDOBhgDOAidA3+BgTBz9UDe6kceKuSLA==,iv:hp/LbndfsKOkmQvyz1mCremVKAvS2mkU6pEQoblPyoI=,tag:30C0oQpJAoRfSKG1pXse2A==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:SljBndr6TwMPfInKgr+4yiptPNY=,iv:p4ppB/QbEL7PKRUl/+OJpzhjitLO9EOGrxFy6WxcRss=,tag:7Mf1J3M93slOIAi/lE7XwA==,type:str]
                - AWS_PAGER=""
            cloud_config:
                aws:
                    networking:
                        public:
                            cidr: 10.0.0.0/16
                            subnets:
                                public:
                                    - 10.0.1.0/24
                                    - 10.0.2.0/24
                                    - 10.0.3.0/24
                                private:
                                    - 10.0.251.0/24
                                    - 10.0.252.0/24
                                    - 10.0.253.0/24
                        private:
                            cidr: 172.17.0.0/16
                            subnets:
                                public:
                                    - 172.17.1.0/24
                                    - 172.17.2.0/24
                                    - 172.17.3.0/24
                                private:
                                    - 172.17.251.0/24
                                    - 172.17.252.0/24
                                    - 172.17.253.0/24
        secrets:
            ssh_key:
                name: ssh-key
                # encrypted
                data: ENC[AES256_GCM,data:GeDSjsaZzafmtXtT3PmdTluR8EQQQGSLhd/XvmiXw7xXvVby05zw4UO7KgjwTvkrmN4D32/SQO+T3CA9s5EoIMjloN1C8t7YKUVmwaksI0Zh7J7rKlFTeDXw1bxS04eywa/YDTmY3LdGBqcHEALbO75WZhLwgTVcw0dX+UKy+hoRzl2hDXD2oE05KVwG05okpv75JY282XfAIUQjmRNvvAGeM0QuKh/e2OUYlV90Sd7gKzr/m8uj9Ei+LAr5IRAX3HNxwtOniSANG7j4m0cE2K1Vvbc+dRJPyDzgBEUNskMDyFB/D8AhooZlAP60jchbVYCkgN9KVeU4VVyg2QI0TGbrcmTjYqH68wkjfhNrQf5MyzvLWzTPGrJXj5ObUZvZPr79DV4itAObl18NsokpYHkre4mP3yXBJrmtnQzT8gpZF25wrgjaHLbZ2rAQkds9xwn2VFuwRDhsS+UMAgmWx70/DUjXZcXMgzU8WlcV1416+Be8RY/mg1ymSeTpSshyn1DSKedmw4dLl3VTYRDT7w7DJDK9U4Y83l6RO2fuZ3giiVexovfbjLrYH9fRDmwzDYgSAzpgY+zj0xT+/+qiEG2f9LNKAtbjLj6YzybH/7TFTwPPGNpo9SPU5LAd3RRsZsKQ+5FFsJHuLelWBU4ySFUhGpp2MrmMEpAH8oPIwJxD29gKKr1se9Ur/QCB46W7ANK9BpwBq67bkx2omIRLUnT8pNJ/yhTFXZxR8XAOHMk/pvsNyHyX4vuIQ8WaKtHNPR7KzANG2HUO6JzGUTAqwv4hswvsLm4LLScouSsJ1V9GjZkkLCphFqg7HyxR6mrLjjmaTHm614FbV75aXe9KMsJXXJl9SFHgxu2dbjRCUhcC15C5to//voKe5U2OKX4wdB+JCHtdvewvCg7QNC0+qkCv0JKmwKOFRiK5ljypzq3JOPVY+jiVFajM9z6ZVU7FDDkuFhFdSNHg4KLVsJ/TaH1GUVySKCA9qMevRi0m/iZJAidrp0fNmNDq3HEV1WNnALx+ZX8ZJtbHTfhnjFK2+rtsaK9yeYo6b4E1ssopBlIDHujJQwXnR0iBzFJlkOuzBxq9ETpfXvstMQe9zqQA0stuwDuT89NFIXIztPqA9CR+pvBU2ELIkwGtmPY63P3PXD4fidyf1mPrGCwSqD1BMZDikGN8PXCQWDOmDw9V7MzpXwekamcwpvHNvBFiAcjtE6djCj0yzV/h0W5vwHMwyx8YPiLq5Q1lQsmkugNwZuDM6YpiF+QP/3/8zVjGDVEJdD8C7umyUWUifNnGRJCr6InE2Y/l6cgKbY1ApWK+YBDANAq4QRMwxy5lQWFCQ07Bj1OCw8boSpI48EkDHSM55+gdNB9f5Pe1Yhf1WKWmlIG2eLYlfTH5FKeuDu6vporbZJkDlwj72xq4YSux1gwJjU4VfptUcDtYNDqFXWOowLz/CyTr7boKTYMQKqkDapGk7BIs2W3EfiqgBj+hezW/hXMWUSrYJurK3CkvHsT5mGHflgCtc53DH9jL5lSug1MUOZmRSDwvW71DqUuoOt1MAVpcZeJjjsehHenB3khshPwskIwYvO5Jramr5uSywhW0AhwcAI+My8aNRq4j2+xm8FQoTT+EMWNwXzAbKIpTxULvhfglZUV5IjOlmsXbmBFweINUN0/4OvrqkaK+cE1iuRBvC+lm/OpAzJbXkAjgZXHsTV475MK3qAklorc8RZKFO4JTGn/wWzp7zhr5oEJlsj204umKe7CjtJiJDUWNYu4+FXRRUdhWImyz4E7GMbP7AXN+0CMq/Z/onA7D/Jw4KPksKqWZl46S9cxYVn+ldZjI+JCAzw2pPUt48tZ7YX7leyCe96728NapHj2GjrzSynwSB+GeRql16rcdhMl/BBGv86mYi3pi0F/zWlX3LUH4ddm2DLMGXXqaTpFMYOZB+VrNjZf3SGo2vJnrQqW9IAu7712Mm6k1/WoNfAQR87nhsqIqDS0dztXuayiwTDisYTj1HbiwVp442DMu+bk5Z9R6RmADRX+bzGobTZFbN0b7d/x8S74m+ecowVyb/xaUZKcYC4j6K48ZT3gVk3qoP/Y1VQOLeywK4ZbsHSBHvogjSgro9DQAFta/vy1U7JQhzhXfxqEpFXlLy/lVIG9/lDWpQPJzlucORawOL7nrAsMMqZyZHMAmPKbIMkz3zJBbDitgaudhk88rfeGkrTcp5lMPd9+0luIz2Jnf1qwnyvBqZx6DeQm+8Wwt2+cm/w4F+EyUxYiEW3eBDjdPkX3huDy/lRX7o9wD33djonisPhf8gEHcdJ1FoU1ifcke53ObgorvdewEjjNikAYMjNVK+HDPdmSjzv4xV/O1041ptmlGXFd1rWJnf+tpI+fXm+cd8TiDfGlLZ7fOUeS/kjA/mjpbnMPSVQTLZ5D+x3LGO90fHIwwoGXaAypmCLrljfQX1up2vwU8UKG/v0jtw+rYpoHGwFPiTWxID2zXW9EqRyBO9Chtxeig3e0kOAkPIglW2fCAu4wU2uVyDRgft9exSVNn/EovWCmifKt7vwCgDPZOOWE1KTHOTNkpHjB8hObBlvQw9epV9rNBzMnCRfewzxZHnOPEE5SDZteJqU/P/jjeUdBx9wVF59GNP9Hewi9+t8EMaQcLvOYDObf+Xb+Fh1lW4myq+F9Co59BtxcFK2ZS0fWMT4LEcqOPjM+p6cJZS33i2AYDzAUDKC35dflDDboZBeoc0+WXOCVv9H5cLIiOIthAMLd3KgYh9F1EhIfN+n+6rrz8wN0qYk4USM3w/p/4p7jB+KXTRRT20ox9j6QDwh5rjKKIuLLzLl+t2CHlJFSSca9NwqIT4+Xke/dUy2r/uFHNRxTIFjaSJM2v2xQlHedrYIp6aXXbTe1qmNM2siF7/kO1IvhrrIJrnzG0tqEnYCHgO4lMi1xdYmpa/yNYBrchnFsv8tzPddHUPCZj5ZFBlTHXqmua55GYdBWOa8hBT7tT/vxNYS7xK40dzFqIHjEZJpF3gk5beZjTrdf6OJvvAEuptDAdTe6DpDC+vRGo7GlzggaBMluQ2qgGn+8UKEfXmw31OFYS9IDH9Up/B27zbBybO/XHVYuULOts9Smkei90xi7TJHlsIX1ltUt6Im+7CAsJqGdnbvvg17uDNIc1jiJ4WG8w3D/fWXN+LGxaHtykOlrE8jc+UPBk4Uzjjp6h1fsTBuSExjj/pR7twCW1+g9wrZJd/8mHXRuYFv7H8SlHzUdWSd/5EXKX99YaBJmZFbiZKYk5jHTj4FasH2teH8Tq2ysnkjoZuixd8accqowrB3tyiQy+9juhaxkz+niZPr/0SwKBzZ0SfWfwUgWsiqSysZOofZmSccEmAgxbpfNwpvRYOlnxNvjvPED6g9w8TXKd4EoUic70oOh/Pg8oDdQaF5wDaP/qyzdH2O/T0Qs5LXcn/keRu3cHdHd0QWnEPKFBtGjP,iv:qSw9KDSfn0RdOieZLcD3ryJhSov1I0HaUrrya6xMh0c=,tag:9Zg6BNfo8szZ47F8izJ4rA==,type:str]
    rosa:
        version: 20260124
        depends_on:
            - ocp-rosa
        alias_of: null
        common_options:
            # common_options.ignore_installconfig_check: Ignores checking for an installconfig in this
            # environment.
            ignore_installconfig_check: true
        deploy:
            environment_vars:
                # encrypted
                - ENC[AES256_GCM,data:guYKv6j7UpFhlPaRG33g3cFCVKhfakK1QXu0wTZ/Lx2i0D7IKdo=,iv:Yf8UlNv20/T9i881BuEudxKw44EMqQpRPiun/3dtLd0=,tag:pCVqH4pc99z7tITEe/LVuQ==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:4lAYrW0svvRjz3tB+6hxGwNACNxkxXUmb2Yg2mFOTySPi1ObZ4pzX6taFdBlM+oQSz3lkMWG8A6OmUjy3/U=,iv:/NwOsP1kUV7Urv/arCQKY2sxK7hPacRE4ZXnciSjVvI=,tag:O0X6RF9NTNOakl7Ez1+Kig==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::829168431290:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:0zy3L3sVDtrqKEy0rWRQ4ALtiaX+Ec5flkhTcB9gTXOseRUWCjZBKbn1yerNKSoOcyA/bQs=,iv:JkiHxfBBlkm7lsAZkfqieXTrTIYrC8lfaQRh4Tos/H8=,tag:wcmwbPCEcBpMAmqGymJAbg==,type:str]
                - AWS_PAGER=""
                # encrypted
                - ENC[AES256_GCM,data:NaWQ9lNWGii9gRsM8ZD6eH4lH87RYhv9+eAjiEjr12Jfo78A/2iBPNF1V9s9Tbu4cu3k,iv:3YY5/q318zgBNcGvH8thQxTRgJ8lnVfLFk5KlEEair0=,tag:RtCkrrnghl291NuVmkEfcA==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:uFVnQVD02n6Oqtc66iWJv9DLL7SmB5tIpHT+cStD6woI7b2gB/xZ+r1NDgnLi7tmhzln,iv:oI3OhoX6TN0uimRabih++nPUDrhtpNNyO1iIlcyzAIk=,tag:Yphaxv1NARnHY/UXW5/GYg==,type:str]
            cluster_config:
                name: rosa-demoland
            cloud_config:
                aws:
                    networking:
                        availability_zones: 3
                        cidr_block: 172.0.0.0/16
    ocp-rosa:
        alias_of: ocp
        deploy:
            node_config:
                bootstrap:
                    ignition_file_s3_key: bootstrap.ign
                    instance_type: m5.xlarge
                    spot: false
                    quantity_per_zone: 1
                control_plane:
                    quantity_per_zone: 1
                    instance_type: m5.xlarge
                    spot: false
                workers:
                    quantity_per_zone: 1
                    instance_type: m5.xlarge
                    spot: false
    ocp:
        version: 20250827
        deploy:
            environment_vars:
                # encrypted
                - ENC[AES256_GCM,data:3z4FU12AZl9uceVSoLie6iwTT5n4f5YfmhIBXTAAk5qFC7mArFA=,iv:KauXDI8Wx0eP1RVpwSsiLMTepe2bRhARSCyosPZrDPE=,tag:CcPIIUjeW3ossv+OzEYD9g==,type:str]
                # encrypted
                - ENC[AES256_GCM,data:G2dMcqPWsKUL0KpLsAI5k99JgKM/1Ol962AGMVxsWrbHHXmZ7ah0HDSmtp46IBFIMkwnNMAg63M/2Aqy53A=,iv:wTTO+TDrAVh44ICgwJ37spE2u/6I+8LXPJB6MRmypEo=,tag:O49BlmGXP8r7HkkG7PnYTA==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::829168431290:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:UvIKwAXZ8YeatpIm1yCEOksEMK/kuk0oJo+cNQ7TI/vmcnpY6JC22Dm6UJCC/D3ZeJ7Ft8U=,iv:ye1xbwLiAmhOjI8db+971grozYU8JTXN5dR9n+Cc5fw=,tag:IzdRi9HYk6nMWBTbv4C4hw==,type:str]
                - AWS_PAGER=""
            cloud_config:
                aws:
                    cloudformation:
                        stack_name: demoland-ocp-aws-cfn
                    networking:
                        dns:
                            domain_name: sandbox1365.opentlc.com
                        cidr_block: 10.0.0.0/16
                        region: us-east-2
                        availability_zones:
                            bootstrap:
                                - us-east-2a
                            control_plane:
                                - us-east-2a
                                - us-east-2b
                                - us-east-2c
                            workers:
                                - us-east-2a
                                - us-east-2b
            cluster_config:
                names:
                    cluster: demoland-ocp-aws
                    infrastructure: demoland-ocp-aws-infra
            node_config:
                common:
                    ignition_file_s3_bucket: s1gdf449ohge-demoland-ocp-ignition-files
                    # encrypted
                    pull_secret: ENC[AES256_GCM,data:Q1svEp/2mSIJgaWVcuwRUXKYZl2Fv5r7pfVapkCpTmHIo6bT1ADKIm9O31aR7wvgHBEYq+VDLpitXpctEAoxGuLMeyg1oCJxPixQA/eB/mf/pKmqFPiZj2TJgVrro0oV88AsvvLzpNFwoyTgaJks8NIy+tyz4i9k19kbZ6FT5VCG8NkKtRdv+SWeKffTUaDjhXbsBEjpE/aBsZal8pMXNSqNnQmsTLdYtDwfUZnI7jYz8con2L0BqsHWRZXEA9UEEeP872F5WzOpAun0viYGcVCqKJYugSvwS6CnvQdyrhRebzaKUF9ltPCTLsrhJGJWbUirJ63maShtO9C2y6J81rPStgmnsojsmHWj7u8Tu9nF/lRoG8+Tc7akivlkS22hPI80X2ecMoMY7kdbIPK/M5tGDNOnxdz/Xlrk9CtTOSkjOC9NhJUGBJCDuua6HoKW5oixj9eWI0jXLw4doTVH9OscE6hwZw1qWqLnCTv8lRIQeA+fEpzqR6TYwHAdNLudyQqfB5BCELN0baZaPtUAie3jYnTPGBcQ6BkMkhPkcnnx1uwWjl/z4reWaELshezm/h5GmFbV3tGFruKvzSA3S3Xzb/JLnuuqlJbH7fBLB/+DRo/dV2jRMdThBAYsjrx9hZfOv9SwQB9SiWxikFut4Gk83kWLBQJ5NuKgvRHYygCqov8ZqQT/S6wX1/+5bhjSe2x41r2irbLYRc4LeqwyQWbpCjyXsg7hYYnH1qOSjocoLOp1i4R3CXx0M3N6re8OdxKYQ8s4MNuXh//uEF/To/NVk4VIKBdIq84Eo3J7EDGDs20GMHXq/K8VRZVt3NXlNGc+j08PdoXO2FAVo8fGtIjANdFt8nnWpcPLPBwCFrUpv8jeBKPEMXT/YwOVIS9JMTwr9dz2cCwln6TXWv1LBMKhk3ZNBMHQm9aSZb3oA0LBRInA2A8tUtQWdkddAEck3Q4Kcfn7qr4NDqJ1XHuum4nTWkEhbZcsWhyLs2FZP8kUD/bt8+qN04dC/OsvhNMs83SbGCNG9iX5DqDvZ3LKof/sKgawJlwowMt/YIXRflWJKcucXx77PueCNDY8ICR9Uwsg+Dn+Cv9e9BceYB3+ng6pLfI7uT6v+3SOfsuaRy8/z3PiNgZT31ZQFPKB6zftvXxqDfJwb841/U+nbsD6ulj6kP2oXr8KBvg31nsBCWyJLcsR1L5JjRRdV0NLgi9cNjsUn4wuB4uz9x7wopMrexs2TLpFxGnMx5yL5svg0/2jkzeg9j3ESGfOLLJvIAUtHHeyOPiCobfMM/m/JYTikUBitSOQQSx8BRMkpv7hEzc+xQGRI0/3QMf8NSD+JnI5VCFwimp2ihJFyjEuUpxpJl86iCRT91DEWjkAuhGthDx1g28nm3+gVbW5MCwElBGxarABZDJ4bfC61ETJv53gqQt2pPAuGGsNJdA1ligWLTkeXC/rTcyg0nWuZwXm5DWowifybOSAQ29jsxUMd2jtQd6jmKUgKAOsvOGvTyRn1qdJhbrr7nePPfDjZ8loRKAAA052bJbcJ3h2t/1yJSDRLPO6RcEnvofUAON+TFkc8WMRJ8qQVowi+iUXRs2U4M6pgVd8d9fmLEydpo2iBRsyjf3Vr0oJVh5LizsUKuhlwKYog6atBfdT5jA5DqUETBy5cAR8q3bcLPImaPFUt0KDbnTtuX7Jx5hDjal4QMWzogFPxDStFgL/FLH5vb9n8xIxQ1dbEuFm1RwJ91+pQUokfibL9+j3HTautTtrAbzB5dEnbvmuEZ/zJJCNXx5YqBoTmLywKy4dJ72Juul+8Q/WxOoQ1K7qbDaDtDjur5OWJ7D1AxnN5NgKMcyjVU7IaaCtfLw2J+Jt7mMSXgrW9nDg8+HKbxPJdmgnqt4MmKsmEXYL7WxNgp9slOz91ri7wH9f8UP37bND9UvN8VGmj4pB4X67SVl0xs6Jj7V3+MMyDdIxLnaGxXA9oTUV8uRJZ5wOCOsaNQe2FZBqn+qdilGiIwqcIYznDxPjGT6FcgO88plTsAK40LoDlO3ZyG1N4YQ1ajjIj+NCE328KjDnWrh3h8QZPbGQQ60n4sV6s6NH+FEFU0uhfwCDO9gsiUHZLU0P++4lajUcW10BPAEFjzgxAfTwrqCAbyidceUAPiQzAuY8atGiaH0Z+e7e1T0Httz45oVufzbJ6Xb32iMARvn1WD0ZmjJ7nRopZnnyj6C69SqbYboHJxU4T1J0r71A3h1j8HGDzKvW4vGVzy23cj9mZTOKs1KjSnWcGsbNxwcS3WeC2SlMUxPvnVN51lF+AOwFxgaF29RqdLr4pS4KjLpqNMrOeBDIlW98maVQftxTjT2RyK/G295Usj+aW/4B/1hShSzobnhP2n1NrbGkOUT4Sn8KYZheIJg5ZRoYvfOj1d6R78+gijOU3XUcZ+4EsGwvOs3ZWVCtm67U+csIF/H7P9w5jvgRcItYzJOyb/GBRnAq0ZqN/vz6r24ep7lSifcm93nfQb11b8d30gLkMMNK2NE77dVlL9nDNpC3+O1FbIArPHJ8nufxkqzqDnjsY6BLZllN7UAlvXhs1h34cPA+hA2L4Te2JPdwsjKiicDeikmXIWcrSfjQI8/cnGRGg8Y2zZ52es+z9NzAZHZwkjgFw6/Q5CSyKPEMM5EG0Z7d5wwPvqJ7fBEiPCzW9YHNpOJqxQNk8El4OKdHwGBsC12uNfiRYxKLDAdV/X6L0+QTsZSF5cBh21NVvoBFONPGoyXm1eEvDpwAK9THpQSgngGjAUc8OzxABK2YAcHN6XMcY+L5fSAMUvwRf170oi3Xxqz+CXS06woKybTyeBidwDb6xdkluWPifUjeXVgb3cOjk0QXOopbgMCDHvkexF5fUJEG7GiUFdiDcXlaCMkVwWNruxdktIn/TKRu3OV9aWT9LNa2xH37Fe2Pcp6gOoMIfld2NicmBv3cIt94hcctoVW+89s67JeqDkdfO1l3AnQSauujuBpbttiUR1v5mFfAciDfTWH8kuefm1FsGjW5V2YBS3Iv7wIIVGL7EerD5XPAGpU+t8NpAI7HZO48y2Q6ciBpoatub+kO4BIJP80/QKUJ5M2OY4pOFJCCPvRblAIbbOZXELegCqSzCX6SO9UcYWxakN1tCEKzDcmMXfZTUL/i2kAy8aSo6WdpVBIXc5xYEj+kB1TKix6hfrSmmatCJWvH7en5ILXxmSdcTg5s58VsEb68H+eoTmB2riVOzK+Ei1iKHQwpDBjWfCE2s7/Aj4oVblC4vxwi1twHYnO2UCeWtKnzIlhv2idYqHZh4vxV9gxGkZ3P1kb76gHESn28w21v1Sb9yBaKbqyB6Uopvuii9Qs4f8uDmsPTVwmJXuXQbmUt3DEZWaLnE3gH+LuVigIXhTczRC4zHh2S8TMdnw79vz9ZJT9LqG+z7sRmnlCUCFSN2Ra+aUH5kr/1vJlce5jAfPA/hsE2kSUsOGffqMauB1novNsj+6Liw9FyXTuz1WPs2mlocCJl1sMrC/Lcr2mHhFPV+H1uzgOML1FGe0DuHA1yJm9VjX+4WSICXbjcS/xpYl4JYjVYDESna3aZNHd/qVtoVoRXUdxroAN0bExpL3sOrelhd176T64V7NHYqo3o6XiuOFv+lAk6ovogDAdDdRswMvo2zFxsXdjttKt+G4/z7JkG3boFbdXpdJay,iv:eQ/2mP9+lNSOgXHhY6v+dkgAhxpH1IL++YGPOgguMdQ=,tag:j4h7/zKX4jLq20SRq0pE3A==,type:str]
                bootstrap:
                    ignition_file_s3_key: bootstrap.ign
                    instance_type: t3.xlarge
                    spot: false
                    quantity_per_zone: 1
                control_plane:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
                workers:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
            secrets:
                ssh_key:
                    name: ocp-aws-ssh-key
                    # encrypted
                    data: ENC[AES256_GCM,data:U2eobbE6upIEWrxHBbiL1zSEMdXQBDwRWpiZyGog9UJMPT/JwpXKdy5pD0wR2O3Gg/QVR2lJH4pZGJum/Xeuccm6/rFfxLP913xX76Ps+W6AP10YowpbOAjcX/bubm+FA5WZnIs0CFr8LUSzmKzrKxv1ITL5vxECbXOseszrMvBnDUoduAj5b8X31/FmPzPJQ1hBIQm66Ko9qB5yY09MpxeWmWOB4ZjR6n2tbsRve886UEq922SdhaldEozb2zq+OC4U1eKBOc4Rq0JoWCam2NnM/Y8vCrgOd9wo5taB+RAR4v+0WqRZlZtFoRxv8L2BAZkuZ3mObqbb5PcH/a/w5HzJ/V82mm5UN3Ie6rBLR1W2SsdWh4ZHE2qhYMpgU/XreRTGwG+/b3hU/z2ik7wgVo7MIXTvDpGqN8tf70IzmMXX2EpHWQMAO4Re+UB8b7GP7xFREbCjC7hnFQoel3AJNUPVdFFsGFdgDHyRa09BamVfnlhWtVfChrY2xl1X5NroZZT7Qn9uOvw6gj7mJhrmbq0JfCaetecTwqY=,iv:/j7qGCxTK0lBUSONjta9cn2A3X4idjk3zamBgFkFLbc=,tag:IR2K25bjQdDe7+KU/OyyCg==,type:str]
sops:
    lastmodified: "2026-02-05T17:57:21Z"
    mac: ENC[AES256_GCM,data:5DiwwjJcugGaKAomq4fYrrLec72wJxPDCAm5j+MaNaho9NboAlMF9MSCNAa7ZvyGNcYH+ffSmcgYpYGCdtsPA4UcTZE+gt6jDwXVOCh0ChXksMe3fV6MxOkUWwKE2VEfF+kqJQRsmiGCKXUzRiAI+/bB3EIqGIZiqQ+Q7Va06co=,iv:AOTG+8xErRRKCckFf2G3ezsGlO33VgAa4SPK8qiWp+k=,tag:vjuLIMFfE4JKHpZgxI9IMw==,type:str]
    pgp:
        - created_at: "2025-08-21T19:30:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYyNh9fWacSISAQdAh1/D/6CIXWPHdZTNp0ZI2lXpcWcYvSQCewb9uwaDJnQw
            ipjRcoFwW+yp4GHfMJcW0j0HE9AMaA2I9rMO0I8uq49axieaTe3ILpfpFrV4ThP7
            1GYBCQIQrc+2di+Am+TGhRxvmQfECHp7X7+ZUwk/TSjKRU8UOdXICAOkhiVVfJuW
            jafsv5O9xj4G1pGPkljda5ej3Ny7Gn25b8WuazE7IMDq7K9u/cheoCWDf9Wln7J7
            QIRW4e2GQ+w=
            =Jv7T
            -----END PGP MESSAGE-----
          fp: E7645036F453F0DA44BED49F49949A5572BF2AE4
    encrypted_comment_regex: ^[ ]{0,}encrypted$
    version: 3.11.0
