environments:
    example:
        version: 20250827
        deploy:
            # environment_vars: Set within the container that provisions/destroys the environment.
            environment_vars:
                - SOME_KEY=some value
                - ANOTHER_KEY=another value
        # these secrets will get mounted into a folder called /secrets within the
        # container that builds your cluster.
        secrets: {}
    ocp:
        version: 20250827
        deploy:
            environment_vars:
                - AWS_ACCESS_KEY_ID=AKIAUZD2QU52MOTFZMIU
                # encrypted
                - ENC[AES256_GCM,data:R54DtxU+eOH+dQj7vfa7FFmgnxU3xGMKtoRA8wldSFCyJqvy3coExCzVMMu0W++l+KzH51skD+Dy6cIULwE=,iv:s1DZeU0zOMVv9NEoQWO8vUAgoSHQ5mi2Ztxgzu7zsYM=,tag:5+bjuuc52QuFE5hR+FxNBA==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::328821942132:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:9iKAyOZvWZcUUYCLbrunGEFRi9zI87Pl9YY5vAbOQ+ZVKSl9uhSi09zAxAWtR5oJYH8bres=,iv:cQwQlYTSslJTdP2+7ClTxjPwdAYICmNxPIBz2Gph6Iw=,tag:eyJMEw0SAq5x1MEhokjRFw==,type:str]
            cloud_config:
                aws:
                    networking:
                        cidr_block: 10.0.0.0/16
                        region: us-east-2
                        availability_zones:
                            bootstrap:
                                - us-east-2a
                            control_plane:
                                - us-east-2a
                                - us-east-2b
                                - us-east-2c
                            workers:
                                - us-east-2a
                                - us-east-2b
            node_config:
                bootstrap:
                    instance_type: t3.xlarge
                    spot: false
                    quantity_per_zone: 1
                control_plane:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
                workers:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
            secrets:
                ssh_key:
                    name: ocp-aws-ssh-key
                    # encrypted
                    data: ENC[AES256_GCM,data:U2eobbE6upIEWrxHBbiL1zSEMdXQBDwRWpiZyGog9UJMPT/JwpXKdy5pD0wR2O3Gg/QVR2lJH4pZGJum/Xeuccm6/rFfxLP913xX76Ps+W6AP10YowpbOAjcX/bubm+FA5WZnIs0CFr8LUSzmKzrKxv1ITL5vxECbXOseszrMvBnDUoduAj5b8X31/FmPzPJQ1hBIQm66Ko9qB5yY09MpxeWmWOB4ZjR6n2tbsRve886UEq922SdhaldEozb2zq+OC4U1eKBOc4Rq0JoWCam2NnM/Y8vCrgOd9wo5taB+RAR4v+0WqRZlZtFoRxv8L2BAZkuZ3mObqbb5PcH/a/w5HzJ/V82mm5UN3Ie6rBLR1W2SsdWh4ZHE2qhYMpgU/XreRTGwG+/b3hU/z2ik7wgVo7MIXTvDpGqN8tf70IzmMXX2EpHWQMAO4Re+UB8b7GP7xFREbCjC7hnFQoel3AJNUPVdFFsGFdgDHyRa09BamVfnlhWtVfChrY2xl1X5NroZZT7Qn9uOvw6gj7mJhrmbq0JfCaetecTwqY=,iv:/j7qGCxTK0lBUSONjta9cn2A3X4idjk3zamBgFkFLbc=,tag:IR2K25bjQdDe7+KU/OyyCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-28T20:19:29Z"
    mac: ENC[AES256_GCM,data:XdqvEdVCen79XD9IOyLrhgo8+5U7UbvaETUHRJnBnPOTvXzm+TZsSH+XMn/kiMuEdW0fk4K56xCCr+NoiNBblaiMd8ytckwHPDO28OlZMePOXb+A4DFbWXnZnfVGwcvmzrf1CHUeXmrpcKkUYtcp/1ceH3zka17BIZ6PPHRUkG0=,iv:l0dS1rC5M03PQWB9H48X8ofA+1sBRV2w9QNGcwtKpWY=,tag:21vWnhPEFtNGFKc7fN6u4A==,type:str]
    pgp:
        - created_at: "2025-08-21T19:30:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYyNh9fWacSISAQdAh1/D/6CIXWPHdZTNp0ZI2lXpcWcYvSQCewb9uwaDJnQw
            ipjRcoFwW+yp4GHfMJcW0j0HE9AMaA2I9rMO0I8uq49axieaTe3ILpfpFrV4ThP7
            1GYBCQIQrc+2di+Am+TGhRxvmQfECHp7X7+ZUwk/TSjKRU8UOdXICAOkhiVVfJuW
            jafsv5O9xj4G1pGPkljda5ej3Ny7Gn25b8WuazE7IMDq7K9u/cheoCWDf9Wln7J7
            QIRW4e2GQ+w=
            =Jv7T
            -----END PGP MESSAGE-----
          fp: E7645036F453F0DA44BED49F49949A5572BF2AE4
    encrypted_comment_regex: ^[ ]{0,}encrypted$
    version: 3.9.3
