environments:
    example:
        version: 20250827
        deploy:
            # environment_vars: Set within the container that provisions/destroys the environment.
            environment_vars:
                - SOME_KEY=some value
                - ANOTHER_KEY=another value
    ocp:
        version: 20250827
        deploy:
            environment_vars:
                - AWS_ACCESS_KEY_ID=AKIAUZD2QU52MOTFZMIU
                # encrypted
                - ENC[AES256_GCM,data:R54DtxU+eOH+dQj7vfa7FFmgnxU3xGMKtoRA8wldSFCyJqvy3coExCzVMMu0W++l+KzH51skD+Dy6cIULwE=,iv:s1DZeU0zOMVv9NEoQWO8vUAgoSHQ5mi2Ztxgzu7zsYM=,tag:5+bjuuc52QuFE5hR+FxNBA==,type:str]
                - DEFAULT_AWS_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::328821942132:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:9iKAyOZvWZcUUYCLbrunGEFRi9zI87Pl9YY5vAbOQ+ZVKSl9uhSi09zAxAWtR5oJYH8bres=,iv:cQwQlYTSslJTdP2+7ClTxjPwdAYICmNxPIBz2Gph6Iw=,tag:eyJMEw0SAq5x1MEhokjRFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-08-27T22:10:00Z"
    mac: ENC[AES256_GCM,data:2ji9ShnxFrfgDKTim4PtpxSkY03zjqyxIcTiyWyowRw3KCtXh3yVE/oA5PS0/e8MgbSDM8eO7as1VRs+LAA1Yn2MRK1TYuS1IHr3J5lcEoWuY9QuhlRB7MY1PnAd0WWl11wZcBfxuHJQxCw6ic/bUSHhVyM6T9v2bgLQ99NR0aU=,iv:plUzN+inxIrsdt3FmkPDOa/nmxzEv7o7GSQEXKBQ36o=,tag:S7KStjuBeuUWdZY4GhVekQ==,type:str]
    pgp:
        - created_at: "2025-08-21T19:30:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYyNh9fWacSISAQdAh1/D/6CIXWPHdZTNp0ZI2lXpcWcYvSQCewb9uwaDJnQw
            ipjRcoFwW+yp4GHfMJcW0j0HE9AMaA2I9rMO0I8uq49axieaTe3ILpfpFrV4ThP7
            1GYBCQIQrc+2di+Am+TGhRxvmQfECHp7X7+ZUwk/TSjKRU8UOdXICAOkhiVVfJuW
            jafsv5O9xj4G1pGPkljda5ej3Ny7Gn25b8WuazE7IMDq7K9u/cheoCWDf9Wln7J7
            QIRW4e2GQ+w=
            =Jv7T
            -----END PGP MESSAGE-----
          fp: E7645036F453F0DA44BED49F49949A5572BF2AE4
    encrypted_comment_regex: ^[ ]{0,}encrypted$
    version: 3.9.3
