environments:
    example:
        version: 20250827
        deploy:
            # environment_vars: Set within the container that provisions/destroys the environment.
            environment_vars:
                - SOME_KEY=some value
                - ANOTHER_KEY=another value
        # these secrets will get mounted into a folder called /secrets within the
        # container that builds your cluster.
        secrets: {}
    ocp:
        version: 20250827
        deploy:
            environment_vars:
                - AWS_ACCESS_KEY_ID=AKIAUZD2QU52MOTFZMIU
                # encrypted
                - ENC[AES256_GCM,data:R54DtxU+eOH+dQj7vfa7FFmgnxU3xGMKtoRA8wldSFCyJqvy3coExCzVMMu0W++l+KzH51skD+Dy6cIULwE=,iv:s1DZeU0zOMVv9NEoQWO8vUAgoSHQ5mi2Ztxgzu7zsYM=,tag:5+bjuuc52QuFE5hR+FxNBA==,type:str]
                - AWS_DEFAULT_REGION=us-east-2
                - AWS_ROLE_ARN=arn:aws:iam::328821942132:role/admin-access-role
                # encrypted
                - ENC[AES256_GCM,data:9iKAyOZvWZcUUYCLbrunGEFRi9zI87Pl9YY5vAbOQ+ZVKSl9uhSi09zAxAWtR5oJYH8bres=,iv:cQwQlYTSslJTdP2+7ClTxjPwdAYICmNxPIBz2Gph6Iw=,tag:eyJMEw0SAq5x1MEhokjRFw==,type:str]
                - AWS_PAGER=""
            cloud_config:
                aws:
                    cloudformation:
                        stack_name: demoland-ocp-aws-cfn
                    networking:
                        dns:
                            domain_name: sandbox587.opentlc.com
                        cidr_block: 10.0.0.0/16
                        region: us-east-2
                        availability_zones:
                            bootstrap:
                                - us-east-2a
                            control_plane:
                                - us-east-2a
                                - us-east-2b
                                - us-east-2c
                            workers:
                                - us-east-2a
                                - us-east-2b
            cluster_config:
                names:
                    cluster: demoland-ocp-aws
                    infrastructure: demoland-ocp-aws-infra
            node_config:
                common:
                    ignition_file_s3_bucket: s1gdf449ohge-demoland-ocp-ignition-files
                    # encrypted
                    pull_secret: ENC[AES256_GCM,data:Q1svEp/2mSIJgaWVcuwRUXKYZl2Fv5r7pfVapkCpTmHIo6bT1ADKIm9O31aR7wvgHBEYq+VDLpitXpctEAoxGuLMeyg1oCJxPixQA/eB/mf/pKmqFPiZj2TJgVrro0oV88AsvvLzpNFwoyTgaJks8NIy+tyz4i9k19kbZ6FT5VCG8NkKtRdv+SWeKffTUaDjhXbsBEjpE/aBsZal8pMXNSqNnQmsTLdYtDwfUZnI7jYz8con2L0BqsHWRZXEA9UEEeP872F5WzOpAun0viYGcVCqKJYugSvwS6CnvQdyrhRebzaKUF9ltPCTLsrhJGJWbUirJ63maShtO9C2y6J81rPStgmnsojsmHWj7u8Tu9nF/lRoG8+Tc7akivlkS22hPI80X2ecMoMY7kdbIPK/M5tGDNOnxdz/Xlrk9CtTOSkjOC9NhJUGBJCDuua6HoKW5oixj9eWI0jXLw4doTVH9OscE6hwZw1qWqLnCTv8lRIQeA+fEpzqR6TYwHAdNLudyQqfB5BCELN0baZaPtUAie3jYnTPGBcQ6BkMkhPkcnnx1uwWjl/z4reWaELshezm/h5GmFbV3tGFruKvzSA3S3Xzb/JLnuuqlJbH7fBLB/+DRo/dV2jRMdThBAYsjrx9hZfOv9SwQB9SiWxikFut4Gk83kWLBQJ5NuKgvRHYygCqov8ZqQT/S6wX1/+5bhjSe2x41r2irbLYRc4LeqwyQWbpCjyXsg7hYYnH1qOSjocoLOp1i4R3CXx0M3N6re8OdxKYQ8s4MNuXh//uEF/To/NVk4VIKBdIq84Eo3J7EDGDs20GMHXq/K8VRZVt3NXlNGc+j08PdoXO2FAVo8fGtIjANdFt8nnWpcPLPBwCFrUpv8jeBKPEMXT/YwOVIS9JMTwr9dz2cCwln6TXWv1LBMKhk3ZNBMHQm9aSZb3oA0LBRInA2A8tUtQWdkddAEck3Q4Kcfn7qr4NDqJ1XHuum4nTWkEhbZcsWhyLs2FZP8kUD/bt8+qN04dC/OsvhNMs83SbGCNG9iX5DqDvZ3LKof/sKgawJlwowMt/YIXRflWJKcucXx77PueCNDY8ICR9Uwsg+Dn+Cv9e9BceYB3+ng6pLfI7uT6v+3SOfsuaRy8/z3PiNgZT31ZQFPKB6zftvXxqDfJwb841/U+nbsD6ulj6kP2oXr8KBvg31nsBCWyJLcsR1L5JjRRdV0NLgi9cNjsUn4wuB4uz9x7wopMrexs2TLpFxGnMx5yL5svg0/2jkzeg9j3ESGfOLLJvIAUtHHeyOPiCobfMM/m/JYTikUBitSOQQSx8BRMkpv7hEzc+xQGRI0/3QMf8NSD+JnI5VCFwimp2ihJFyjEuUpxpJl86iCRT91DEWjkAuhGthDx1g28nm3+gVbW5MCwElBGxarABZDJ4bfC61ETJv53gqQt2pPAuGGsNJdA1ligWLTkeXC/rTcyg0nWuZwXm5DWowifybOSAQ29jsxUMd2jtQd6jmKUgKAOsvOGvTyRn1qdJhbrr7nePPfDjZ8loRKAAA052bJbcJ3h2t/1yJSDRLPO6RcEnvofUAON+TFkc8WMRJ8qQVowi+iUXRs2U4M6pgVd8d9fmLEydpo2iBRsyjf3Vr0oJVh5LizsUKuhlwKYog6atBfdT5jA5DqUETBy5cAR8q3bcLPImaPFUt0KDbnTtuX7Jx5hDjal4QMWzogFPxDStFgL/FLH5vb9n8xIxQ1dbEuFm1RwJ91+pQUokfibL9+j3HTautTtrAbzB5dEnbvmuEZ/zJJCNXx5YqBoTmLywKy4dJ72Juul+8Q/WxOoQ1K7qbDaDtDjur5OWJ7D1AxnN5NgKMcyjVU7IaaCtfLw2J+Jt7mMSXgrW9nDg8+HKbxPJdmgnqt4MmKsmEXYL7WxNgp9slOz91ri7wH9f8UP37bND9UvN8VGmj4pB4X67SVl0xs6Jj7V3+MMyDdIxLnaGxXA9oTUV8uRJZ5wOCOsaNQe2FZBqn+qdilGiIwqcIYznDxPjGT6FcgO88plTsAK40LoDlO3ZyG1N4YQ1ajjIj+NCE328KjDnWrh3h8QZPbGQQ60n4sV6s6NH+FEFU0uhfwCDO9gsiUHZLU0P++4lajUcW10BPAEFjzgxAfTwrqCAbyidceUAPiQzAuY8atGiaH0Z+e7e1T0Httz45oVufzbJ6Xb32iMARvn1WD0ZmjJ7nRopZnnyj6C69SqbYboHJxU4T1J0r71A3h1j8HGDzKvW4vGVzy23cj9mZTOKs1KjSnWcGsbNxwcS3WeC2SlMUxPvnVN51lF+AOwFxgaF29RqdLr4pS4KjLpqNMrOeBDIlW98maVQftxTjT2RyK/G295Usj+aW/4B/1hShSzobnhP2n1NrbGkOUT4Sn8KYZheIJg5ZRoYvfOj1d6R78+gijOU3XUcZ+4EsGwvOs3ZWVCtm67U+csIF/H7P9w5jvgRcItYzJOyb/GBRnAq0ZqN/vz6r24ep7lSifcm93nfQb11b8d30gLkMMNK2NE77dVlL9nDNpC3+O1FbIArPHJ8nufxkqzqDnjsY6BLZllN7UAlvXhs1h34cPA+hA2L4Te2JPdwsjKiicDeikmXIWcrSfjQI8/cnGRGg8Y2zZ52es+z9NzAZHZwkjgFw6/Q5CSyKPEMM5EG0Z7d5wwPvqJ7fBEiPCzW9YHNpOJqxQNk8El4OKdHwGBsC12uNfiRYxKLDAdV/X6L0+QTsZSF5cBh21NVvoBFONPGoyXm1eEvDpwAK9THpQSgngGjAUc8OzxABK2YAcHN6XMcY+L5fSAMUvwRf170oi3Xxqz+CXS06woKybTyeBidwDb6xdkluWPifUjeXVgb3cOjk0QXOopbgMCDHvkexF5fUJEG7GiUFdiDcXlaCMkVwWNruxdktIn/TKRu3OV9aWT9LNa2xH37Fe2Pcp6gOoMIfld2NicmBv3cIt94hcctoVW+89s67JeqDkdfO1l3AnQSauujuBpbttiUR1v5mFfAciDfTWH8kuefm1FsGjW5V2YBS3Iv7wIIVGL7EerD5XPAGpU+t8NpAI7HZO48y2Q6ciBpoatub+kO4BIJP80/QKUJ5M2OY4pOFJCCPvRblAIbbOZXELegCqSzCX6SO9UcYWxakN1tCEKzDcmMXfZTUL/i2kAy8aSo6WdpVBIXc5xYEj+kB1TKix6hfrSmmatCJWvH7en5ILXxmSdcTg5s58VsEb68H+eoTmB2riVOzK+Ei1iKHQwpDBjWfCE2s7/Aj4oVblC4vxwi1twHYnO2UCeWtKnzIlhv2idYqHZh4vxV9gxGkZ3P1kb76gHESn28w21v1Sb9yBaKbqyB6Uopvuii9Qs4f8uDmsPTVwmJXuXQbmUt3DEZWaLnE3gH+LuVigIXhTczRC4zHh2S8TMdnw79vz9ZJT9LqG+z7sRmnlCUCFSN2Ra+aUH5kr/1vJlce5jAfPA/hsE2kSUsOGffqMauB1novNsj+6Liw9FyXTuz1WPs2mlocCJl1sMrC/Lcr2mHhFPV+H1uzgOML1FGe0DuHA1yJm9VjX+4WSICXbjcS/xpYl4JYjVYDESna3aZNHd/qVtoVoRXUdxroAN0bExpL3sOrelhd176T64V7NHYqo3o6XiuOFv+lAk6ovogDAdDdRswMvo2zFxsXdjttKt+G4/z7JkG3boFbdXpdJay,iv:eQ/2mP9+lNSOgXHhY6v+dkgAhxpH1IL++YGPOgguMdQ=,tag:j4h7/zKX4jLq20SRq0pE3A==,type:str]
                bootstrap:
                    ignition_file_s3_key: bootstrap.ign
                    instance_type: t3.xlarge
                    spot: false
                    quantity_per_zone: 1
                control_plane:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
                workers:
                    quantity_per_zone: 1
                    instance_type: t3.xlarge
                    spot: false
            secrets:
                ssh_key:
                    name: ocp-aws-ssh-key
                    # encrypted
                    data: ENC[AES256_GCM,data:U2eobbE6upIEWrxHBbiL1zSEMdXQBDwRWpiZyGog9UJMPT/JwpXKdy5pD0wR2O3Gg/QVR2lJH4pZGJum/Xeuccm6/rFfxLP913xX76Ps+W6AP10YowpbOAjcX/bubm+FA5WZnIs0CFr8LUSzmKzrKxv1ITL5vxECbXOseszrMvBnDUoduAj5b8X31/FmPzPJQ1hBIQm66Ko9qB5yY09MpxeWmWOB4ZjR6n2tbsRve886UEq922SdhaldEozb2zq+OC4U1eKBOc4Rq0JoWCam2NnM/Y8vCrgOd9wo5taB+RAR4v+0WqRZlZtFoRxv8L2BAZkuZ3mObqbb5PcH/a/w5HzJ/V82mm5UN3Ie6rBLR1W2SsdWh4ZHE2qhYMpgU/XreRTGwG+/b3hU/z2ik7wgVo7MIXTvDpGqN8tf70IzmMXX2EpHWQMAO4Re+UB8b7GP7xFREbCjC7hnFQoel3AJNUPVdFFsGFdgDHyRa09BamVfnlhWtVfChrY2xl1X5NroZZT7Qn9uOvw6gj7mJhrmbq0JfCaetecTwqY=,iv:/j7qGCxTK0lBUSONjta9cn2A3X4idjk3zamBgFkFLbc=,tag:IR2K25bjQdDe7+KU/OyyCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-09-04T21:12:49Z"
    mac: ENC[AES256_GCM,data:8/xT8axtuE7at3RCH8GEYkwW8w9PVhqoUtlZdjfTxcsI/MZCigUQu4MWPC1M1eSjMr4eyfMIoNtIoSyOohHIGEkkyasm4pAQ42f/sPP9KtANXtVEALBvxE99gqFnqvOLWDCuwWT56bqevJxoOXbdrRIH4NhBhW8ZTlpfX1g9O/M=,iv:4RknR2mryLQztGkDHuqQasJZob0zRiYHkqWMUjEk4Vc=,tag:mpje5gFXS+pCiYT3lauLow==,type:str]
    pgp:
        - created_at: "2025-08-21T19:30:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DYyNh9fWacSISAQdAh1/D/6CIXWPHdZTNp0ZI2lXpcWcYvSQCewb9uwaDJnQw
            ipjRcoFwW+yp4GHfMJcW0j0HE9AMaA2I9rMO0I8uq49axieaTe3ILpfpFrV4ThP7
            1GYBCQIQrc+2di+Am+TGhRxvmQfECHp7X7+ZUwk/TSjKRU8UOdXICAOkhiVVfJuW
            jafsv5O9xj4G1pGPkljda5ej3Ny7Gn25b8WuazE7IMDq7K9u/cheoCWDf9Wln7J7
            QIRW4e2GQ+w=
            =Jv7T
            -----END PGP MESSAGE-----
          fp: E7645036F453F0DA44BED49F49949A5572BF2AE4
    encrypted_comment_regex: ^[ ]{0,}encrypted$
    version: 3.9.3
