Parameters:
  InfrastructureName:
    AllowedPattern: ^([a-zA-Z][a-zA-Z0-9\-]{0,26})$
    MaxLength: 27
    MinLength: 1
    ConstraintDescription: Infrastructure name must be alphanumeric, start with a letter, and have a maximum of 27 characters.
    Description: A short, unique cluster ID used to tag cloud resources and identify items owned or used by the cluster.
    Type: String
  EksClusterRoleArn:
    Description: ARN of the EKS cluster IAM role.
    Type: String
  EksWorkerNodeRoleArn:
    Description: ARN of the EKS cluster worker node IAM role.
    Type: String
  EksWorkerNodeInstanceProfileArn:
    Description: ARN of the EKS cluster worker node IAM instance profile.
    Type: String
  RepoName:
    Description: The name of the repository.
    Type: String
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Join ["/", [!Ref InfrastructureName, !Ref RepoName]]
Outputs:
  RepositoryUri:
    Description: URI of the ECR repo.
    Value: !GetAtt Repository.RepositoryUri
