apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: instrumentation
  namespace: openshift-opentelemetry-operator
  annotations:
      instrumentation.opentelemetry.io/otel-go-auto-target-exe: '/opt/app-root/gobinary'
spec:
  exporter:
    endpoint: http://otel-collector.openshift-opentelemetry-operator.svc.cluster.local:4318
  env:
    - name: OTEL_EXPORTER_OTLP_TIMEOUT
      value: "20"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
