apiVersion: v1
kind: Secret
metadata:
  name: rhobs-secret
  namespace: openshift-observability
stringData:
  forcepathstyle: "true"
  bucketnames: replace me
  region: replace me
  endpoint: replace me
  access_key_id: replacement
  access_key_secret: replacement

