apiVersion: v1
kind: ConfigMap
metadata:
  name: rhdh-config
  namespace: rhdh
data:
  app-config.yaml: |-
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    auth:
      environment: production
      providers:
        github:
          production:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
    signInPage: github
    catalog:
      providers:
        githubOrg:
          id: github-${GITHUB_ORG}
          githubUrl: "${GITHUB_URL}"
          orgs: [ "${GITHUB_ORG}" ]
          schedule:
            frequency:
              minutes: 30
            initialDelay:
              seconds: 15
            timeout:
              minutes: 15
