FROM curlimages/curl AS ocp_installer
ARG OPENSHIFT_VERSION
ENV OPENSHIFT_VERSION="${OPENSHIFT_VERSION:-4.19}"
ENV OPENSHIFT_BINARIES_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}"
RUN \
  url="${OPENSHIFT_BINARIES_URL}/openshift-install-linux"; \
  uname -m | grep -Eq 'arm|aarch' && url="${url}-arm64"; \
  >&2 echo "Downloading OpenShift Installer from URL: $url"; \
  curl -o /tmp/file.tar.gz "${url}.tar.gz"
RUN tar -xvzf /tmp/file.tar.gz -C /tmp

FROM curlimages/curl AS oc_client
ARG OPENSHIFT_VERSION
ENV OPENSHIFT_VERSION="${OPENSHIFT_VERSION:-4.19}"
ENV OPENSHIFT_BINARIES_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}"
RUN \
  url="${OPENSHIFT_BINARIES_URL}/openshift-client-linux"; \
  uname -m | grep -Eq 'arm|aarch' && url="${url}-arm64"; \
  curl -o /tmp/file.tar.gz "${url}.tar.gz"
RUN tar -xvzf /tmp/file.tar.gz -C /tmp

FROM fedora:41 AS final
COPY --from=ocp_installer /tmp/openshift-install /usr/bin/openshift-install
COPY --from=oc_client /tmp/oc /usr/bin/oc
RUN dnf -y update
RUN dnf -y install yq jq openssh ssh-agent htpasswd bsdtar
RUN arch=amd64; uname -m | grep -Eiq 'arm|aarch' && arch=arm64; \
    curl -Lo /usr/bin/ytt "https://github.com/carvel-dev/ytt/releases/download/v0.52.0/ytt-linux-$arch"
RUN chmod +x /usr/bin/ytt
RUN ytt --version
RUN arch=x86_64; uname -m | grep -Eiq 'arm|aarch' && arch=aarch64; \
  cat >/etc/yum.repos.d/google-cloud-sdk.repo <<-EOF
[google-cloud-cli]
name=Google Cloud CLI
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-$arch
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF
RUN sudo dnf -y install libxcrypt-compat google-cloud-cli
RUN curl -L "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" | bsdtar -C /tmp -xf - && \
    chmod -R +x /tmp/aws && \
    /tmp/aws/install
