#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: auto-import-secret
  namespace: #@ data.values.cluster_name
  managedcluster-import-controller.open-cluster-management.io/keeping-auto-import-secret: ""
stringData:
  kubeconfig: #@ data.values.cluster_kubeconfig
