#@ load("@ytt:data", "data")
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: #@ data.values.bucket
      endpoint: #@ data.values.endpoint
      insecure: true
      access_key: #@ data.values.access_key_id
      secret_key: #@ data.values.secret_access_key
