apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-cm
  namespace: replace-me
data:
  services: |-
    service-1.namespace-1.svc.cluster.local:1234
    service-2.namespace-2.svc.cluster.local:1234
    service-3.namespace-3.svc.cluster.local:1234
