---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-everybody
    component: traffic-generator
  name: traffic-generator
  namespace: replace-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-everybody
      component: traffic-generator
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-everybody
        component: traffic-generator
    spec:
      containers:
        - image: curlimages/curl
          name: app
          env:
            - name: SERVICES
              valueFrom:
                configMapKeyRef:
                  name: traffic-generator-cm
                  key: services
          command:
            - sh
            - -c
            - |-
              >&2 echo "Starting traffic generator. CTRL-C to quit."
              num_services=$(echo "$SERVICES" | wc -l)
              while true
              do
                svc=$(echo "$SERVICES" | gsed -n "$(shuf -i 1-${num-services} -n 1)p" |
                  sed -E 's;http(s?)://; |
                  cut -f1 -d '.')
                >&2 echo "===> I'm talking to '$svc'"
                curl -sS "$svc"
              done
