AWSTemplateFormatVersion: 2010-09-09
Description: Template for OpenShift Cluster User
Parameters:
  InfrastructureName:
    Description: Name of infrastructure for cluster
    Type: String
  UserNameBase:
    Description: Prefix for user name.
    Type: String
    MaxLength: 32
    ConstraintDescription: User name must be less than 32 characters.
  PolicyArns:
    Description: Policies to attach to the user.
    Type: String
Resources:
  User:
    Type: AWS::IAM::User
    Properties:
      UserName: !Join
        - "-"
        - - !Ref UserNameBase
          - user
          - !Ref InfrastructureName
      ManagedPolicyArns: !Split
        - ","
        - !Ref PolicyArns
  Credentials:
    Type: AWS::IAM::AccessKey
    Properties:
      Status: Active
      UserName: !Ref User
Outputs:
  AccessKey:
    Value: !Ref Credentials
  SecretAccessKey:
    Value: !GetAtt Credentials.SecretAccessKey
