FROM curlimages/curl AS oc_client
ENV OPENSHIFT_VERSION=4.20.14
ENV OPENSHIFT_BINARIES_URL="https://mirror.openshift.com/pub/openshift-v4/clients/ocp/${OPENSHIFT_VERSION}"
RUN \
  url="${OPENSHIFT_BINARIES_URL}/openshift-client-linux"; \
  uname -m | grep -Eq 'arm|aarch' && url="${url}-arm64"; \
  curl -o /tmp/file.tar.gz "${url}.tar.gz"
RUN tar -xvzf /tmp/file.tar.gz -C /tmp

FROM fedora:43 AS final
RUN dnf -y update
RUN dnf -y install yq jq
COPY --from=oc_client /tmp/oc /usr/bin/oc

