---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: simple-load-tester-web-server
  namespace: replace-me
  labels:
    app: simple-load-tester
    component: web-server
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-load-tester-web-server
  namespace: replace-me
  labels:
    app: simple-load-tester
    component: web-server
spec:
  source:
    git:
      uri: https://github.com/jlhidalgo/golang-web-server
      ref: main
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang:1.18-ubi9
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: web-server-app-image:latest
  triggers:
    - type: ConfigChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-load-tester
    component: web-server
  name: simple-load-tester-web-server
  namespace: replace-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-load-tester
      component: web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-load-tester
        component: web-server
    spec:
      containers:
        - image: web-server-app-image:latest
          name: app
          ports:
          - containerPort: 8081
          resources: {}
          command:
            - ./bin/web-server
status: {}

