---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: simple-load-tester-web-server
  namespace: replace-me
  labels:
    app: simple-load-tester
    component: web-server
spec:
  lookupPolicy:
    local: true
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: simple-load-tester-web-server
  namespace: replace-me
  labels:
    app: simple-load-tester
    component: web-server
spec:
  source:
    git:
      uri: https://github.com/codeskyblue/gohttpserver
      ref: master
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: golang:1.18-ubi9
        namespace: openshift
  output:
    to:
      kind: ImageStreamTag
      name: simple-load-tester-web-server:latest
  triggers:
    - type: ConfigChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-load-tester
    component: web-server
  name: simple-load-tester-web-server
  namespace: replace-me
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "simple-load-tester-web-server"
          },
          "fieldPath": "spec.template.spec.containers[?(@.name==\"app\")].image"
        }
      ]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-load-tester
      component: web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-load-tester
        component: web-server
    spec:
      containers:
        - image: simple-load-tester-web-server
          name: app
          ports:
          - containerPort: 8081
          resources: {}
status: {}

