apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-load-tester
    component: web-server
  name: simple-load-tester-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-load-tester
      component: web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-load-tester
        component: web-server
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/app-image:latest
          name: app
          ports:
          - containerPort: 8081
          resources: {}
          command:
            - ./bin/web-server
status: {}

