apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-load-tester
    component: web-server
  name: simple-load-tester-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-load-tester
      component: web-server
  strategy: {}
  template:
    metadata:
      labels:
        app: simple-load-tester
        component: web-server
    spec:
      containers:
      - image: registry.redhat.io/rhel9/nginx-124
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
        command:
          - nginx
          - -g
          - "daemon off;"
status: {}

