FROM curlimages/curl AS virtctl
RUN \
  url="https://github.com/kubevirt/kubevirt/releases/download/v1.9.0/virtctl-v1.9.0-linux-amd64"; \
  uname -m | grep -Eq 'arm|aarch' && url=$(echo "$url" | sed 's/amd64/arm64/g'); \
  curl -Lo /tmp/virtctl "$url" && chmod +x /tmp/virtctl

FROM demoland-base
COPY --from=virtctl /tmp/virtctl /usr/local/bin/virtctl
